### ISSUE TITLE
Memory leak when unmounting component

### ISSUE THREAD

**Issue by pdugan20** [kirankalyan5/react-native-segmented-control-tab#312]
If I logout of my application and unmount the component, I get the following error:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
at node_modules/react/cjs/react.development.js:471:2 in Component.prototype.setState
at node_modules/react-native-segmented-control-tab/src/SegmentedControlTab.js:65:26 in handleTabPress
at [native code]:null in flushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```

Any ideas on how to handle this?

**Comment by kirankalyan5** [comment]
@pdugan20 I suspect the leak is related to the state update in the consumer app, could you share/explain what you are doing with `handleTabPress`?

**Comment by pdugan20** [comment]
Hello! I don't believe I have access to handleTabPress(). I am passing in the following functions to onTabPress() based on whether the control tab allows single or multiple selected items.

```
    handleSingleSelect = (index, type) => {
        const { selectedIndices } = this.state;
        selectedIndices[type] = index;

        this.setState({ selectedIndices });
    };

    handleMultipleSelect = (index, type) => {
        const { selectedIndices } = this.state;

        if (selectedIndices[type].includes(index)) {
            selectedIndices[type] = selectedIndices[type].filter(
                (item) => item !== index,
            );
        } else {
            selectedIndices[type].push(index);
        }

        this.setState({ selectedIndices });
    };
```
